### ISSUE TITLE
MASSIVE ISSUE WITH CODE

### ISSUE THREAD

**Issue by Vivek-Aggala** [dhruvnps/pathfinder#2]
When testing the code I encountered a catastrophic error.  The supposed pathfinder goes through the wall hence destroying its very existence

![image](https://user-images.githubusercontent.com/71449499/132652279-b8a83b17-74ca-407d-a8d9-2c53eec04001.png)

**Comment by dhruvnps** [comment]
Can you send a screenshot of the entire screen

**Comment by Vivek-Aggala** [comment]
![image](https://user-images.githubusercontent.com/71449499/132652708-07875176-7214-4fc6-8e7a-cfb89e65347c.png)

**Comment by xXSandro-EnukidzeXx** [comment]
As can be seen in my compatriot's prior logged issue, a bug in the code leads to a apocalyptic, cataclysmic error invalidating its raison d'etre

**Comment by dhruvnps** [comment]
bug fixed 6913bb589791704e750b1d50c4117eb4671946fc
